export type ProductFee = {
  id: string;
  name: string;
  path: string;
  groupId: string;
  adminRegular: number;
  adminMall: number;
  serviceRegular: number;
  serviceSpecial: number;
  keywords: string;
};

type FeeRow = [
  name: string,
  path: string,
  groupId: string,
  adminRegular: number,
  adminMall: number,
  serviceRegular: number,
  keywords?: string,
];

const SPECIAL_SERVICE_RATE: Record<number, number> = {
  1: 2.5,
  2: 3.5,
  3.5: 5,
  5.5: 7,
  6: 7.5,
  6.5: 8,
  7.5: 9,
  8: 9.5,
};

const ROWS: FeeRow[] = [
  // Produk populer dan contoh yang paling sering dicari.
  [
    "Pakaian Muslim Wanita",
    "Fashion › Fashion Muslim › Pakaian Muslim Wanita",
    "fashion",
    10,
    9.95,
    8,
    "gamis abaya tunik kaftan baju kurung set muslim dress menyusui pakaian syari",
  ],
  [
    "Mukena & Perlengkapan Sholat",
    "Fashion › Fashion Muslim › Mukena & Perlengkapan Sholat",
    "fashion",
    8.25,
    9.95,
    7.5,
    "mukena dewasa mukena travel sajadah peci set perlengkapan shalat ibadah",
  ],
  [
    "Makanan Ringan",
    "FMCG › Makanan & Minuman › Makanan Ringan",
    "fmcg",
    9.5,
    10.2,
    6,
    "snack keripik biskuit wafer camilan kacang popcorn",
  ],
  [
    "Handphone",
    "Elektronik › Handphone & Tablet › Handphone",
    "electronics",
    5.25,
    4.7,
    1,
    "hp smartphone ponsel android iphone",
  ],
  [
    "Skincare",
    "FMCG › Perawatan & Kecantikan › Perawatan Wajah",
    "beauty",
    8.25,
    9.95,
    5.5,
    "serum toner sunscreen pelembap moisturizer face wash essence",
  ],
  [
    "Buku Bacaan",
    "Lifestyle › Buku & Alat Tulis › Buku Bacaan",
    "home",
    9,
    7.2,
    6,
    "novel buku fisik agama bisnis anak pendidikan komik",
  ],

  // Fashion.
  [
    "Gamis, Abaya & Kaftan",
    "Fashion › Fashion Muslim › Pakaian Muslim Wanita",
    "fashion",
    10,
    9.95,
    8,
    "gamis abaya kaftan dress muslim wanita",
  ],
  [
    "Tunik & Atasan Muslim Wanita",
    "Fashion › Fashion Muslim › Pakaian Muslim Wanita",
    "fashion",
    10,
    9.95,
    8,
    "tunik blouse kemeja dalaman atasan menyusui muslim wanita",
  ],
  [
    "Bawahan Muslim Wanita",
    "Fashion › Fashion Muslim › Pakaian Muslim Wanita",
    "fashion",
    10,
    9.95,
    8,
    "rok celana legging palazzo bawahan muslim wanita",
  ],
  [
    "Baju Olahraga Muslim",
    "Fashion › Fashion Muslim › Pakaian Muslim Wanita",
    "fashion",
    10,
    11.7,
    8,
    "sportwear olahraga muslim syari training",
  ],
  [
    "Baju Renang Muslim",
    "Fashion › Fashion Muslim › Pakaian Muslim Wanita",
    "fashion",
    10,
    11.7,
    8,
    "burkini pakaian renang muslim wanita",
  ],
  [
    "Hijab & Aksesoris Hijab",
    "Fashion › Fashion Muslim › Hijab",
    "fashion",
    8.25,
    9.95,
    7.5,
    "jilbab kerudung khimar pashmina segi empat ciput bros",
  ],
  [
    "Pakaian Muslim Pria",
    "Fashion › Fashion Muslim › Pakaian Muslim Pria",
    "fashion",
    8.25,
    9.95,
    7.5,
    "koko gamis pria sarung baju melayu celana muslim",
  ],
  [
    "Pakaian Muslim Anak",
    "Fashion › Fashion Muslim › Pakaian Muslim Anak",
    "fashion",
    8.25,
    9.95,
    7.5,
    "hijab anak mukena anak baju koko gamis set muslim anak",
  ],
  [
    "Outerwear Fashion Muslim",
    "Fashion › Fashion Muslim › Outerwear",
    "fashion",
    8.25,
    9.95,
    7.5,
    "rompi jaket mantel cardigan muslim",
  ],
  [
    "Pakaian Wanita",
    "Fashion › Pakaian Wanita",
    "fashion",
    8.25,
    9.95,
    7.5,
    "atasan dress rok celana jeans jaket wanita",
  ],
  [
    "Pakaian Pria",
    "Fashion › Pakaian Pria",
    "fashion",
    8.25,
    9.95,
    6.5,
    "kaos kemeja celana jeans jaket sweater pria",
  ],
  [
    "Sepatu Pria",
    "Fashion › Sepatu Pria",
    "fashion",
    9,
    10.2,
    6.5,
    "sneakers sandal formal boots pria",
  ],
  [
    "Sepatu Wanita",
    "Fashion › Sepatu Wanita",
    "fashion",
    9,
    10.2,
    6.5,
    "heels flat sandal sneakers boots wanita",
  ],
  [
    "Tas Pria",
    "Fashion › Tas Pria",
    "fashion",
    9,
    10.2,
    7.5,
    "ransel selempang pinggang dompet pria",
  ],
  [
    "Tas Wanita",
    "Fashion › Tas Wanita",
    "fashion",
    9,
    10.2,
    7.5,
    "handbag tote ransel selempang dompet wanita",
  ],
  [
    "Koper & Tas Travel",
    "Fashion › Koper & Tas Travel",
    "fashion",
    9,
    10.2,
    7.5,
    "koper travel luggage organizer paspor",
  ],
  [
    "Tas Duffel",
    "Fashion › Koper & Tas Travel › Tas Duffel",
    "fashion",
    10,
    11.7,
    8,
    "duffle gym bag tas olahraga travel",
  ],
  [
    "Jam Tangan",
    "Fashion › Jam Tangan",
    "fashion",
    9,
    10.2,
    8,
    "watch jam analog digital strap",
  ],
  [
    "Aksesoris Fashion",
    "Fashion › Aksesoris Fashion",
    "fashion",
    9,
    10.2,
    8,
    "aksesoris rambut anting cincin gelang kalung dasi ikat pinggang kacamata syal topi",
  ],
  [
    "Masker Fashion",
    "Fashion › Aksesoris Tambahan › Masker",
    "fashion",
    8.25,
    10.45,
    7.5,
    "mask kain penutup wajah fashion",
  ],
  [
    "Kaos Kaki & Stocking",
    "Fashion › Kaos Kaki & Stocking",
    "fashion",
    10,
    10.2,
    6.5,
    "socks kaos kaki stocking legging tipis",
  ],
  [
    "Fashion Bayi & Anak",
    "Fashion › Fashion Bayi & Anak",
    "baby",
    9,
    10.2,
    5.5,
    "baju anak pakaian bayi sepatu anak tas anak",
  ],
  [
    "Logam Mulia",
    "Fashion › Perhiasan › Logam Mulia",
    "premium",
    4.25,
    3.2,
    2,
    "emas batangan perak mulia investasi",
  ],
  [
    "Perhiasan Berharga",
    "Fashion › Perhiasan › Perhiasan Berharga",
    "premium",
    4.25,
    3.2,
    2,
    "emas berlian perak kalung cincin gelang",
  ],
  [
    "Perhiasan Bayi & Anak",
    "Fashion › Fashion Bayi & Anak › Perhiasan",
    "premium",
    4.25,
    9.95,
    2,
    "gelang anting kalung cincin bayi anak",
  ],

  // FMCG, kecantikan, kesehatan, ibu dan bayi.
  [
    "Susu Formula & Makanan Bayi",
    "FMCG › Ibu & Bayi › Makanan Bayi",
    "baby",
    6.75,
    7.7,
    5.5,
    "sufor mpasi bubur puree snack bayi",
  ],
  [
    "Vitamin & Suplemen Bayi",
    "FMCG › Ibu & Bayi › Kesehatan Bayi",
    "baby",
    6.5,
    7.2,
    5.5,
    "vitamin anak minyak ikan suplemen bayi",
  ],
  [
    "Popok & Pispot",
    "FMCG › Ibu & Bayi › Popok & Pispot",
    "baby",
    9,
    7.2,
    5.5,
    "diapers popok sekali pakai clodi toilet training",
  ],
  [
    "Perlengkapan Mandi Bayi",
    "FMCG › Ibu & Bayi › Perlengkapan Mandi",
    "baby",
    8.25,
    7.2,
    5.5,
    "bak mandi handuk sabun shampoo bayi",
  ],
  [
    "Pompa ASI & Perlengkapan Menyusui",
    "FMCG › Ibu & Bayi › Perlengkapan Menyusui",
    "baby",
    9.5,
    10.2,
    5.5,
    "breast pump botol asi kantong asi nursing",
  ],
  [
    "Mainan Bayi",
    "FMCG › Ibu & Bayi › Mainan Bayi",
    "baby",
    10,
    10.2,
    8,
    "rattle teether balok puzzle inflatable perosotan",
  ],
  [
    "Keamanan & Travelling Bayi",
    "FMCG › Ibu & Bayi › Keamanan & Travelling",
    "baby",
    9.5,
    10.2,
    5.5,
    "baby monitor stroller car seat pagar pengaman gendongan",
  ],
  [
    "Telur",
    "FMCG › Makanan & Minuman › Telur",
    "fmcg",
    6.5,
    6.2,
    6,
    "telur ayam bebek puyuh",
  ],
  [
    "Bahan Baking",
    "FMCG › Makanan & Minuman › Bahan Baking",
    "fmcg",
    6.75,
    6.2,
    6,
    "tepung ragi cokelat masak baking powder",
  ],
  [
    "Bahan Pokok",
    "FMCG › Makanan & Minuman › Bahan Pokok",
    "fmcg",
    6.75,
    6.2,
    6,
    "beras mie pasta biji-bijian seafood kering minyak gula",
  ],
  [
    "Kebutuhan Memasak",
    "FMCG › Makanan & Minuman › Kebutuhan Memasak",
    "fmcg",
    6.75,
    6.2,
    6,
    "bumbu saus kecap kaldu rempah santan",
  ],
  [
    "Makanan Segar & Beku",
    "FMCG › Makanan & Minuman › Segar & Beku",
    "fmcg",
    6.75,
    9.95,
    6,
    "frozen food daging ikan sayur buah nugget sosis",
  ],
  [
    "Makanan Instan",
    "FMCG › Makanan & Minuman › Makanan Instan",
    "fmcg",
    9,
    7.2,
    6,
    "mie instan makanan siap saji lauk instan",
  ],
  [
    "Permen & Cokelat",
    "FMCG › Makanan & Minuman › Makanan Ringan",
    "fmcg",
    9.5,
    10.2,
    6,
    "candy gummy tablet candy coklat permen susu lozenges",
  ],
  [
    "Roti & Kue",
    "FMCG › Makanan & Minuman › Roti & Kue",
    "fmcg",
    9,
    10.2,
    6,
    "bakery cake cookies bolu pastry roti",
  ],
  [
    "Minuman",
    "FMCG › Makanan & Minuman › Minuman",
    "fmcg",
    9.5,
    10.2,
    6,
    "kopi teh jus sirup serbuk minuman soda air mineral",
  ],
  [
    "Susu & Produk Olahan",
    "FMCG › Makanan & Minuman › Susu & Olahan",
    "fmcg",
    8.25,
    10.2,
    6,
    "susu bubuk uht yogurt keju krimer whey",
  ],
  [
    "Es Krim",
    "FMCG › Makanan & Minuman › Es Krim",
    "fmcg",
    6.75,
    9.95,
    6,
    "ice cream gelato sorbet",
  ],
  [
    "Set Hadiah & Hampers Makanan",
    "FMCG › Makanan & Minuman › Hampers",
    "fmcg",
    9.5,
    10.2,
    6,
    "parcel hampers gift set makanan minuman",
  ],
  [
    "Makeup",
    "FMCG › Perawatan & Kecantikan › Makeup",
    "beauty",
    8.25,
    9.95,
    5.5,
    "lipstick cushion foundation bedak mascara eyeliner",
  ],
  [
    "Parfum & Wewangian",
    "FMCG › Perawatan & Kecantikan › Parfum",
    "beauty",
    8.25,
    9.95,
    5.5,
    "perfume eau de parfum body mist fragrance",
  ],
  [
    "Perawatan Rambut",
    "FMCG › Perawatan & Kecantikan › Rambut",
    "beauty",
    8.25,
    9.95,
    5.5,
    "shampoo conditioner hair tonic serum rambut",
  ],
  [
    "Perawatan Tubuh",
    "FMCG › Perawatan & Kecantikan › Tubuh",
    "beauty",
    8.25,
    9.95,
    5.5,
    "body lotion scrub sabun deodorant body care",
  ],
  [
    "Vitamin & Suplemen",
    "FMCG › Kesehatan › Suplemen Makanan",
    "health",
    9,
    7.2,
    6,
    "multivitamin herbal protein collagen kapsul tablet",
  ],
  [
    "Obat Bebas & Obat Tradisional",
    "FMCG › Kesehatan › Obat",
    "health",
    9.5,
    7.7,
    6,
    "otc jamu herbal balsem minyak angin",
  ],
  [
    "Alat Kesehatan",
    "FMCG › Kesehatan › Alat Kesehatan",
    "health",
    9,
    7.2,
    6,
    "tensimeter termometer glucometer nebulizer oksimeter",
  ],
  [
    "Perawatan Diri",
    "FMCG › Kesehatan › Perawatan Diri",
    "health",
    9,
    7.2,
    6,
    "sikat gigi pasta gigi pembalut tampon popok dewasa",
  ],
  [
    "Lensa Kontak",
    "FMCG › Kesehatan › Perawatan Mata",
    "health",
    9,
    9.95,
    8,
    "softlens contact lens cairan lensa",
  ],
  [
    "Kesehatan Seksual",
    "FMCG › Kesehatan › Kesehatan Seksual",
    "health",
    9,
    7.7,
    5.5,
    "kondom pelumas tes kehamilan",
  ],
  [
    "Hand Sanitizer",
    "FMCG › Kesehatan › Hand Sanitizer",
    "health",
    10,
    10.2,
    5.5,
    "pembersih tangan antiseptik alkohol",
  ],

  // Elektronik, handphone, komputer, kamera dan gaming.
  [
    "Tablet",
    "Elektronik › Handphone & Tablet › Tablet",
    "electronics",
    5.25,
    4.7,
    1,
    "ipad tablet android",
  ],
  [
    "Laptop",
    "Elektronik › Komputer & Aksesoris › Laptop",
    "electronics",
    5.25,
    4.2,
    1,
    "notebook ultrabook macbook chromebook",
  ],
  [
    "Desktop",
    "Elektronik › Komputer & Aksesoris › Desktop",
    "electronics",
    5.25,
    4.2,
    1,
    "pc komputer all in one mini pc",
  ],
  [
    "Monitor",
    "Elektronik › Komputer & Aksesoris › Monitor",
    "electronics",
    5.25,
    4.2,
    1,
    "display layar monitor gaming",
  ],
  [
    "Komponen Desktop & Laptop",
    "Elektronik › Komputer & Aksesoris › Komponen",
    "electronics",
    5.25,
    4.2,
    2,
    "ram motherboard vga gpu processor cpu psu casing fan",
  ],
  [
    "Printer & Scanner",
    "Elektronik › Komputer & Aksesoris › Printer & Scanner",
    "electronics",
    5.25,
    4.2,
    2,
    "printer inkjet laser scanner tinta",
  ],
  [
    "Penyimpanan Data",
    "Elektronik › Komputer & Aksesoris › Penyimpanan Data",
    "electronics",
    5.25,
    4.2,
    3.5,
    "ssd hdd harddisk flashdisk memory card nas",
  ],
  [
    "Proyektor & Aksesoris",
    "Elektronik › Komputer & Aksesoris › Proyektor",
    "electronics",
    5.25,
    4.2,
    3.5,
    "projector screen presenter",
  ],
  [
    "Keyboard & Mouse",
    "Elektronik › Komputer & Aksesoris › Keyboard & Mouse",
    "electronics",
    6.75,
    7.2,
    5.5,
    "keyboard mechanical mouse trackpad",
  ],
  [
    "Perangkat Network",
    "Elektronik › Komputer & Aksesoris › Network",
    "electronics",
    6.75,
    7.7,
    5.5,
    "router switch access point wifi lan",
  ],
  [
    "Software",
    "Elektronik › Komputer & Aksesoris › Software",
    "electronics",
    6.75,
    10.2,
    5.5,
    "lisensi aplikasi sistem operasi antivirus",
  ],
  [
    "Aksesoris Handphone",
    "Elektronik › Handphone & Tablet › Aksesoris",
    "electronics",
    10,
    10.2,
    5.5,
    "casing charger kabel tongsis holder tempered glass",
  ],
  [
    "Powerbank, Modem & USB",
    "Elektronik › Handphone & Tablet › Aksesoris",
    "electronics",
    6.75,
    7.2,
    5.5,
    "power bank modem dongle usb otg",
  ],
  [
    "Earphone, Headphone & Headset",
    "Elektronik › Audio › Earphone & Headphone",
    "electronics",
    6.75,
    7.2,
    5.5,
    "tws earbuds headphone headset",
  ],
  [
    "Speaker, Mikrofon & Mixer",
    "Elektronik › Audio",
    "electronics",
    9,
    7.2,
    5.5,
    "speaker bluetooth soundbar mic microphone amplifier mixer",
  ],
  [
    "Sound Card",
    "Elektronik › Audio › Sound Card",
    "electronics",
    6.5,
    4.7,
    5.5,
    "audio interface external dac",
  ],
  [
    "Televisi & Aksesoris",
    "Elektronik › Elektronik Rumah › Televisi",
    "electronics",
    6.5,
    7.2,
    5.5,
    "tv smart tv remote bracket antena",
  ],
  [
    "Peralatan Listrik Besar",
    "Elektronik › Elektronik Rumah › Peralatan Besar",
    "electronics",
    6.5,
    7.2,
    5.5,
    "mesin cuci ac kulkas freezer kipas",
  ],
  [
    "Perangkat Dapur Elektrik",
    "Elektronik › Elektronik Rumah › Perangkat Dapur",
    "electronics",
    6.5,
    7.2,
    5.5,
    "rice cooker blender oven mixer air fryer dispenser",
  ],
  [
    "Peralatan Listrik Kecil",
    "Elektronik › Elektronik Rumah › Peralatan Kecil",
    "electronics",
    6.5,
    6.2,
    5.5,
    "setrika purifier vacuum mesin jahit",
  ],
  [
    "Flosser Elektrik",
    "Elektronik › Elektronik Rumah › Perawatan Diri",
    "electronics",
    6.5,
    6.2,
    6,
    "water flosser dental irrigator",
  ],
  [
    "Kelistrikan",
    "Elektronik › Kelistrikan",
    "electronics",
    10,
    10.2,
    6.5,
    "saklar stop kontak bel alarm anti petir fitting kabel listrik",
  ],
  [
    "Kamera & Lensa",
    "Elektronik › Kamera & Drone › Kamera & Lensa",
    "electronics",
    6.5,
    7.2,
    5.5,
    "mirrorless dslr camera lens action cam",
  ],
  [
    "Drone & Aksesoris",
    "Elektronik › Kamera & Drone › Drone",
    "electronics",
    6.5,
    7.2,
    5.5,
    "quadcopter propeller battery drone",
  ],
  [
    "Aksesoris Kamera",
    "Elektronik › Kamera & Drone › Aksesoris",
    "electronics",
    9.5,
    10.2,
    5.5,
    "tripod gimbal lighting flash tas kamera",
  ],
  [
    "Kamera Keamanan & CCTV",
    "Elektronik › Kamera & Drone › Kamera Keamanan",
    "electronics",
    9.5,
    7.7,
    5.5,
    "cctv ip camera dashcam nvr dvr",
  ],
  [
    "Smartwatch & Perangkat Wearable",
    "Elektronik › Perangkat Wearable",
    "electronics",
    9.5,
    7.7,
    5.5,
    "smart watch fitness tracker gps wearable",
  ],
  [
    "Konsol & Video Game",
    "Elektronik › Gaming › Konsol & Game",
    "electronics",
    9.5,
    7.7,
    5.5,
    "playstation xbox nintendo game controller",
  ],
  [
    "Rokok Elektronik",
    "Elektronik › Rokok Elektronik",
    "electronics",
    9,
    7.2,
    5.5,
    "vape pod mod coil liquid",
  ],
  [
    "Baterai & Media Player",
    "Elektronik › Elektronik Lainnya",
    "electronics",
    9.5,
    7.7,
    5.5,
    "battery baterai android box media player",
  ],
  [
    "Walkie Talkie",
    "Elektronik › Elektronik Lainnya › Walkie Talkie",
    "electronics",
    9,
    7.2,
    5.5,
    "radio komunikasi ht handy talky",
  ],
  [
    "Kartu Perdana",
    "Elektronik › Handphone & Tablet › Kartu Perdana",
    "electronics",
    9,
    7.2,
    5.5,
    "sim card kartu seluler starter pack",
  ],

  // Lifestyle, otomotif, buku, hobi, hewan dan rumah.
  [
    "Mobil (Unit Kendaraan)",
    "Lifestyle › Mobil › Unit Kendaraan",
    "automotive",
    2.5,
    2.5,
    7.5,
    "mobil baru bekas kendaraan utuh",
  ],
  [
    "Sepeda Motor (Unit Kendaraan)",
    "Lifestyle › Sepeda Motor › Unit Kendaraan",
    "automotive",
    2.5,
    2.5,
    7.5,
    "motor baru bekas kendaraan utuh",
  ],
  [
    "Aksesoris & Suku Cadang Mobil",
    "Lifestyle › Mobil › Aksesoris & Suku Cadang",
    "automotive",
    8.25,
    10.45,
    7.5,
    "sparepart interior eksterior cover karpet wiper",
  ],
  [
    "Aksesoris & Suku Cadang Motor",
    "Lifestyle › Sepeda Motor › Aksesoris & Suku Cadang",
    "automotive",
    8.25,
    10.45,
    7.5,
    "sparepart shock knalpot lampu spion kampas",
  ],
  [
    "Helm",
    "Lifestyle › Sepeda Motor › Helm",
    "automotive",
    8.25,
    10.45,
    7.5,
    "helmet full face half face visor",
  ],
  [
    "Oli & Pelumas",
    "Lifestyle › Otomotif › Oli & Pelumas",
    "automotive",
    9,
    10.45,
    7.5,
    "oli mesin grease lubricant coolant",
  ],
  [
    "Alat Tulis",
    "Lifestyle › Buku & Alat Tulis › Alat Tulis",
    "home",
    9,
    7.2,
    5.5,
    "pulpen pensil spidol penghapus penggaris",
  ],
  [
    "Perlengkapan Sekolah & Kantor",
    "Lifestyle › Buku & Alat Tulis › Sekolah & Kantor",
    "home",
    9.5,
    7.7,
    5.5,
    "map binder stapler kalkulator label arsip",
  ],
  [
    "Perlengkapan Menggambar",
    "Lifestyle › Buku & Alat Tulis › Menggambar",
    "home",
    10,
    11.7,
    5.5,
    "cat kuas kanvas sketchbook crayon",
  ],
  [
    "Buku Tulis & Kertas",
    "Lifestyle › Buku & Alat Tulis › Buku Tulis & Kertas",
    "home",
    9,
    7.2,
    6,
    "notebook agenda hvs art paper kertas foto",
  ],
  [
    "E-Book",
    "Lifestyle › Buku & Alat Tulis › E-Book",
    "home",
    9,
    7.2,
    5.5,
    "ebook buku digital pdf",
  ],
  [
    "Komik & Buku Audio",
    "Lifestyle › Buku & Alat Tulis › Komik & Audio",
    "home",
    9.5,
    7.7,
    5.5,
    "manga comic audiobook",
  ],
  [
    "Majalah & Koran",
    "Lifestyle › Buku & Alat Tulis › Majalah & Koran",
    "home",
    10,
    11.7,
    5.5,
    "magazine newspaper tabloid",
  ],
  [
    "Bubble Wrap & Bahan Packing",
    "Lifestyle › Perlengkapan Rumah › Bahan Packing",
    "home",
    9.5,
    7.7,
    5.5,
    "bubble wrap kardus lakban polymailer packaging",
  ],
  [
    "Souvenir & Hadiah",
    "Lifestyle › Hobi & Koleksi › Souvenir & Hadiah",
    "home",
    9,
    10.45,
    7.5,
    "gift kado merchandise hampers plakat",
  ],
  [
    "Mainan & Games",
    "Lifestyle › Hobi & Koleksi › Mainan & Games",
    "home",
    9.5,
    7.7,
    8,
    "board game puzzle boneka diecast lego",
  ],
  [
    "Koleksi & Action Figure",
    "Lifestyle › Hobi & Koleksi › Koleksi",
    "home",
    9.5,
    7.7,
    8,
    "action figure kartu koleksi model kit photocard",
  ],
  [
    "Alat Musik & Aksesoris",
    "Lifestyle › Hobi & Koleksi › Musik",
    "home",
    9.5,
    7.7,
    6,
    "gitar keyboard drum ukulele senar stand musik",
  ],
  [
    "Makanan & Aksesoris Hewan",
    "Lifestyle › Hewan Peliharaan",
    "home",
    9.5,
    7.7,
    8,
    "pet food kucing anjing litter kandang leash mainan hewan",
  ],
  [
    "Grooming & Pakaian Hewan",
    "Lifestyle › Hewan Peliharaan › Perawatan",
    "home",
    9.5,
    7.7,
    7.5,
    "shampoo sisir baju kucing anjing grooming",
  ],
  [
    "Peralatan Olahraga & Outdoor",
    "Lifestyle › Olahraga & Outdoor › Peralatan",
    "home",
    10,
    11.7,
    8,
    "fitness gym camping hiking bola raket sepeda tenda",
  ],
  [
    "Pakaian & Sepatu Olahraga",
    "Lifestyle › Olahraga & Outdoor › Fashion Olahraga",
    "home",
    10,
    11.7,
    7.5,
    "jersey training sepatu lari legging sport",
  ],
  [
    "Jas Hujan",
    "Lifestyle › Olahraga & Outdoor › Jas Hujan",
    "home",
    8.25,
    10.45,
    7.5,
    "raincoat ponco mantel hujan",
  ],
  [
    "Furniture",
    "Lifestyle › Perlengkapan Rumah › Furniture",
    "home",
    10,
    11.7,
    6.5,
    "meja kursi lemari rak sofa bangku",
  ],
  [
    "Perlengkapan Kamar Tidur",
    "Lifestyle › Perlengkapan Rumah › Kamar Tidur",
    "home",
    10,
    11.7,
    6.5,
    "kasur bantal guling sprei selimut",
  ],
  [
    "Dekorasi Rumah & Organizer",
    "Lifestyle › Perlengkapan Rumah › Dekorasi",
    "home",
    10,
    11.7,
    8,
    "hiasan dinding vas karpet organizer storage",
  ],
  [
    "Perlengkapan Kamar Mandi",
    "Lifestyle › Perlengkapan Rumah › Kamar Mandi",
    "home",
    10,
    11.7,
    7.5,
    "rak kamar mandi shower ember keset",
  ],
  [
    "Peralatan Makan",
    "Lifestyle › Perlengkapan Rumah › Peralatan Makan",
    "home",
    10,
    11.7,
    5.5,
    "piring mangkuk gelas sendok garpu",
  ],
  [
    "Perlengkapan Dapur",
    "Lifestyle › Perlengkapan Rumah › Dapur",
    "home",
    10,
    11.7,
    8,
    "panci wajan pisau talenan rak dapur",
  ],
  [
    "Taman, Pertukangan & Alat Pengaman",
    "Lifestyle › Perlengkapan Rumah › Taman & Perkakas",
    "home",
    10,
    11.7,
    7.5,
    "bor obeng tang gembok cctv manual alat kebun pot",
  ],
  [
    "Perawatan Rumah",
    "Lifestyle › Perlengkapan Rumah › Perawatan Rumah",
    "home",
    9,
    10.45,
    7.5,
    "tisu pembersih detergen sabun pel pewangi",
  ],
  [
    "Lampu",
    "Lifestyle › Perlengkapan Rumah › Lampu",
    "home",
    9.5,
    7.7,
    6.5,
    "bohlam led lampu meja lampu tidur",
  ],
  [
    "Perlengkapan Menjahit",
    "Lifestyle › Hobi & Koleksi › Menjahit",
    "home",
    9.5,
    7.7,
    6.5,
    "benang jarum kain resleting kancing",
  ],
  [
    "Sealer",
    "Lifestyle › Perlengkapan Rumah › Peralatan Dapur › Sealer",
    "home",
    6.5,
    7.2,
    5.5,
    "impulse sealer vacuum sealer perekat plastik",
  ],
  [
    "Perlengkapan Keagamaan Rumah",
    "Lifestyle › Perlengkapan Rumah › Keagamaan",
    "home",
    10,
    11.7,
    5.5,
    "alquran tasbih sajadah dekorasi religi kitab",
  ],

  // Tiket, voucher dan layanan.
  [
    "E-Money",
    "Tiket, Voucher & Layanan › E-Money",
    "digital",
    8.25,
    7.7,
    7.5,
    "uang elektronik saldo dompet digital kartu tol",
  ],
  [
    "Voucher Gaming",
    "Tiket, Voucher & Layanan › Gaming",
    "digital",
    9,
    7.2,
    5.5,
    "top up game diamond voucher game",
  ],
  [
    "Voucher Belanja",
    "Tiket, Voucher & Layanan › Belanja",
    "digital",
    9.5,
    7.7,
    5.5,
    "retail gift card voucher toko",
  ],
  [
    "Jasa & Layanan",
    "Tiket, Voucher & Layanan › Layanan",
    "digital",
    9.5,
    7.7,
    5.5,
    "service jasa desain servis konsultasi",
  ],
  [
    "Listrik, Gas & Air",
    "Tiket, Voucher & Layanan › Tagihan",
    "digital",
    9.5,
    7.7,
    5.5,
    "pln token listrik pdam gas tagihan",
  ],
  [
    "Voucher Makanan & Minuman",
    "Tiket, Voucher & Layanan › Makanan & Minuman",
    "digital",
    9.5,
    7.7,
    5.5,
    "dine in takeaway restoran cafe voucher",
  ],
  [
    "Streaming",
    "Tiket, Voucher & Layanan › Streaming",
    "digital",
    9.5,
    7.7,
    5.5,
    "film musik subscription langganan",
  ],
  [
    "Pulsa & Paket Data",
    "Tiket, Voucher & Layanan › Telco",
    "digital",
    9.5,
    7.7,
    5.5,
    "pulsa internet paket data telpon sms",
  ],
  [
    "Tiket Event",
    "Tiket, Voucher & Layanan › Tiket Event",
    "digital",
    9.5,
    7.7,
    5.5,
    "konser seminar workshop pameran",
  ],
  [
    "Travel & Tour",
    "Tiket, Voucher & Layanan › Travel & Tour",
    "digital",
    9.5,
    7.7,
    5.5,
    "wisata hotel trip rafting tur paket perjalanan",
  ],
  [
    "Saldo Iklan Shopee",
    "Tiket, Voucher & Layanan › Shopee › Saldo Iklan",
    "digital",
    9.5,
    7.7,
    5.5,
    "ads iklan shopee top up saldo",
  ],
];

function slugify(value: string) {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export function normalizeFeeSearch(value: string) {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

export const PRODUCT_FEES: ProductFee[] = ROWS.map(
  (
    [
      name,
      path,
      groupId,
      adminRegular,
      adminMall,
      serviceRegular,
      keywords = "",
    ],
    index,
  ) => ({
    id: `${slugify(name)}-${index + 1}`,
    name,
    path,
    groupId,
    adminRegular,
    adminMall,
    serviceRegular,
    serviceSpecial:
      SPECIAL_SERVICE_RATE[serviceRegular] ?? serviceRegular,
    keywords,
  }),
);

export function searchProductFees(query: string, limit = 12) {
  const normalized = normalizeFeeSearch(query);
  if (!normalized) return PRODUCT_FEES.slice(0, limit);

  const tokens = normalized.split(/\s+/).filter(Boolean);
  return PRODUCT_FEES.map((product, index) => {
    const name = normalizeFeeSearch(product.name);
    const haystack = normalizeFeeSearch(
      `${product.name} ${product.path} ${product.keywords}`,
    );
    let score = 0;

    if (name === normalized) score += 100;
    if (name.startsWith(normalized)) score += 55;
    if (name.includes(normalized)) score += 35;
    if (tokens.every((token) => haystack.includes(token))) score += 20;
    score += tokens.filter((token) => name.includes(token)).length * 8;
    score += tokens.filter((token) => haystack.includes(token)).length * 2;

    return { product, score, index };
  })
    .filter((item) => item.score > 0)
    .sort((a, b) => b.score - a.score || a.index - b.index)
    .slice(0, limit)
    .map((item) => item.product);
}
